### ISSUE TITLE
to_pandas() throws a type error

### ISSUE THREAD

**Issue by naddeoa** [whylabs/whylogs#1122]
## Description

Repro repo here as well: https://github.com/naddeoa/repro-type-error-whylogs

```
from whylogs.core import DatasetProfile

profile = DatasetProfile()
profile.track({'a': 2})
print(profile.view().to_pandas())

```

Running that gives this error

```
Traceback (most recent call last):
  File "/home/anthony/workspace/python-whylogs-container-demo/whylogs_config/repro.py", line 5, in <module>
    print(profile.view().to_pandas())
  File "/home/anthony/workspace/python-whylogs-container-demo/.venv/lib/python3.10/site-packages/whylogs/core/view/dataset_profile_view.py", line 411, in to_pandas
    df = pd.DataFrame(all_dicts)
TypeError: _StubClass() takes no arguments
```

**Comment by jamie256** [comment]
Are you asking for a pandas dataframe when you don't have pandas installed? I think you can avoid calling to_pandas if you don't want pandas?

whylogs should throw a better error in this case, so its clear what the root cause is. Technically we don't require pandas, but to_pandas should throw in this case.

**Comment by naddeoa** [comment]
Yeah that was it. I had reinstalled whylogs and I didn't reinstall pandas.
