### ISSUE TITLE
Cannot upload segmented result set

### ISSUE THREAD

**Issue by christinedraper** [whylabs/whylogs#1364]
Using whylogs 1.3.3 and whylogs-client 0.5.6, I cannot upload a segmented result set:

```
import os
import whylogs as why
import pandas as pd
import datetime

from whylogs.api.writer.whylabs import WhyLabsWriter
from whylogs.core import DatasetSchema
from whylogs.core.segmentation_partition import segment_on_column

os.environ["WHYLABS_DEFAULT_ORG_ID"] = 'org-xxxx'
os.environ["WHYLABS_DEFAULT_DATASET_ID"] = 'model-92'
os.environ["WHYLABS_API_KEY"] = 'xxxx'

columns = ['testme', 'key']
data = [
    ['one', '1'],
    ['two', '2'],
]

profile = why.log(pd.DataFrame(data, columns=columns), schema=DatasetSchema(segments=segment_on_column('key')))
# Following gives "You must pass either a DatasetProfile or a DatasetProfileView in order to use this writer!"
# WhyLabsWriter(api_key=api_key, org_id=org_id, dataset_id=dataset_id).write(profile)

# Following works if you remove the segment schema, but otherwise fails with "A profile was requested from a segmented result set without specifying which segment to return"
# why.init(org_id=org_id, default_dataset_id=dataset_id, whylabs_api_key=api_key)
# WhyLabsWriter(api_key=api_key, org_id=org_id, dataset_id=dataset_id).write(profile.profile())
```

**Comment by jamie256** [comment]
@richard-rogers can you triage?

**Comment by jamie256** [comment]
The way we have historically supported writing result sets was to do this
```
# result_set = profile in the above example.

result_set.writer("whylabs").write()
```

Does that still work? Maybe this is a bug specific to the new writing of result sets with the WhyLabsWriter.

**Comment by richard-rogers** [comment]
It looks like `[Segmented]ResultSet::writer("whylabs").write()` is the preferred way to do this, and my testing worked for both segmented and unsegmented profiles.

If you call `why.init()`, then `why.log()` will also successfully upload [un]segmented profiles.

For segmented profiles, `WhyLabsWriter(...).option(reference_profile_name="foo").write(segmented_result_set)` works, but the profile ends up in a different s3 location because the reference profile is (must be) set. I'm not sure that asymmetry is intended. At present, you can't pass it an unsegmented `ResultSet`, but you can pass it a `DatasetProfile` or `DatasetProfileView` obtained from one.

**Comment by christinedraper** [comment]
I think I ended up going back to the `WhyLabsWriter` pattern because the `profile.writer.option(api_key=api_key).option(org_id=org_id)` stopped working. That could have been related to the api key change rather than the why.init change. I'll have to go back and re-experiment.

**Comment by FelipeAdachi** [comment]
Solved on https://github.com/whylabs/whylogs/pull/1379
