### ISSUE TITLE
Check previous writen profiles during rotation

### ISSUE THREAD

**Issue by lalmei** [whylabs/whylogs#194]
`should_rotate()` should check previous saved loggers, load and add to previous one or create new logger.

**Comment by andyndang** [comment]
I don't think this an issue. We should not load data back since you might have two writers, and there's no way for us to handle a race condition.

A better solution is to use session ID/session timestamp in the file name when users don't specify a `filename_template`.

The default template should be `profiles.$start_time-$end_time_exclusive.$session_time.bin`
Example: `profiles.2021-03-16T00:00:00.000Z_2021-03-17T00:00:00.000Z.2021-03-26T23:01:15.765Z`

**Comment by lalmei** [comment]
the profiles with log rotation already have start time and interval set, the problem is syncing the start times, which i think is the same problem you are foreboding. Will close this issue for now.
