### ISSUE TITLE
`Writer.path_suffix` fails with no name specified

### ISSUE THREAD

**Issue by ibackus** [whylabs/whylogs#29]
When no name is specified, `Writer.path_suffix` can break output by returning a path suffix starting with '/'.  Later path joining uses `os.path` (probably not good behavior) and can make this the root, overriding other path output.

**Comment by shubhamcodez** [comment]
Is it creating a problem in the script? I'm asking because it is not mentioned why overriding is a bad thing here.

There are several ways manipulation can be done according to the os.path documentation.

**Comment by andyndang** [comment]
This was due to path template logic using `string.Template` class.

This only happens when you create a DatasetProfile without a name, which would not happen if you interact via `Session` object.

We probably will restrict the DatasetProfile to having names and perform validation on path template logic

**Comment by jamie256** [comment]
There is no longer a path_suffix for writers in 1.0.0, you can specify a base_dir in LocalWriter or this defaults to os.getcwd()
