### ISSUE TITLE
[Enhancement/Performance] Don't use TypedConverters on each ColumnTracker update.

### ISSUE THREAD

**Issue by ramannanda9** [whylabs/whylogs#310]
:wave:

What? 

Allow Strict types for ``ColumnProfile`` and prevent inferring types on each update? 
This is currently done here on each track invocation. 
[Code here](https://github.com/whylabs/whylogs/blob/a31a11645f501ffadc59505ddbf33c8881a12969/src/whylogs/core/columnprofile.py#L119)

Why?

The method [here](https://github.com/whylabs/whylogs/blob/a31a11645f501ffadc59505ddbf33c8881a12969/src/whylogs/core/types/typeddataconverter.py#L52
) is slow to call in python, especially if done on each invocation, this adds up. 

How?

1. Allow passing of column type 
2. Determine from first value

**Comment by jamie256** [comment]
Good suggestion! looking into pulling this into some of the pending work we have going.

1) Do you want to infer the value type once (first non-empty value?) and then bind the column profile to that type or do you want to specify the column type explicitly?

2) If a column profile has strict typing, and we encounter a value not consistent with that type what is the desired behavior?

**Comment by ramannanda9** [comment]
1. Inferring on first non empty value seems fine, although a configuration option could also be provided.
2. It should raise error with strict typing.

**Comment by ramannanda9** [comment]
Just bumping this up. 

We wrote a wrapper on datasketches and have seen significantly better performance for things. 

Two things we avoided from whylogs implementation. 

1. Inferring datatype on columns
2. Creating copies on tracker update. 

Encoding sketches:
1. Base 64 encoding. 

Some performance comparisons:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-dcbb4279-7fff-628e-d4b7-b070cd06722d"><div dir="ltr" style="margin-left:0pt;" align="left">

Table Size | Metric Computation Time(whylogs) | Metric Computation Time(Wrapper around datasketches)
-- | -- | --
1.2M x 32 | 5 mins | 51 seconds
34M x 43 | 33 mins | 2.58 minutes
83M x 119 | 38 mins | 5.88 minutes
288M x 43 | 40 mins | 7.8 mins

</div></b>

In our implementation, we have this base class. I think the implementation on whylogs side could be simplified.  

```python
@dataclass_json
@dataclass
class Metric(abc.ABC):
    @classmethod
    @abc.abstractmethod
    def name(cls) -> str:
        pass

    @abc.abstractmethod
    def track(self, val: Any) -> "Metric":
        pass

    @abc.abstractmethod
    def merge(self, other: "Metric") -> "Metric":
        pass

    def serialize(self) -> Dict[str, Any]:
        return {"name": self.name(), "data": self.to_dict()}

    @classmethod
    def deserialize(cls, data: Dict[str, Any]) -> "Metric":
        clazz = find_subclass(cls, data["name"])
        return clazz.from_dict(data["data"])

    @abc.abstractmethod
    def summary(self) -> Dict[str, Any]:
        pass

```
A simple HistogramMetric prototype is shown below:

```python
@dataclass_json
@dataclass
class HistogramMetric(Metric):
    histogram: datasketches.kll_floats_sketch = field(
        default=datasketches.kll_floats_sketch(DEFAULT_HIST_K),
        metadata=config(
            encoder=functools.partial(serde.encode_sketch, "serialize", "deserialize"),
            decoder=serde.decode_sketch,
        ),
    )

    @classmethod
    def name(cls) -> str:
        return "histogram_metric"

    def track(self, val: Any) -> "Metric":
        if pd.isna(val):
            return self
        self.histogram.update(val)
        return self

    def merge(self, other: "Metric") -> "Metric":
        hist_copy = datasketches.kll_floats_sketch.deserialize(
            self.histogram.serialize()
        )
        hist_copy.merge(other.histogram)
        return HistogramMetric(hist_copy)

    def summary(self) -> Dict[str, Any]:
        # ... returns summary cdf, pmf, quantiles, median etc. 
        }

```

**Comment by jamie256** [comment]
Nice on capturing some data here, thanks! I'll pull this into current work to support a lighter weight whylogs-core.

**Comment by jamie256** [comment]
**Fixed in v1**:

Some of the design changes in whylogs 1.0.0 were motivated by this kind of performance analysis, I wanted to share the latest numbers using whylogs==1.0.0 on a Databricks cluster running 10.4 with c5.2xlarge spot instances.

The main function we benchmarked was ```collect_dataset_profile_view(df)``` with various DataFrame sizes based on this original issue.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-dcbb4279-7fff-628e-d4b7-b070cd06722d"><div dir="ltr" style="margin-left:0pt;" align="left">

Table Size | metric computation time (whylogs 1.0.0)
-- | --
1.2M x 32 | 4 seconds
34M x 43 | 33 seconds
83M x 119 | 1.7 minutes
290M x 43 | 2.7 mins

</div></b>

We no longer run TypedConverters on each input. Additionally we have customization and extensibility points in the new API where you can change which trackers are run on a column by choosing a different [resolver ](https://github.com/whylabs/whylogs/blob/mainline/python/whylogs/core/resolvers.py) for the datatype->trackers or by specifying your inputs [schema ](https://github.com/whylabs/whylogs/blob/mainline/python/whylogs/core/schema.py) and we have some examples around these and other use cases here: https://github.com/whylabs/whylogs/tree/mainline/python/examples
