### ISSUE TITLE
Whylogs not adding data profile to mlflow run

### ISSUE THREAD

**Issue by pimonteiro** [whylabs/whylogs#457]
Hi, I was trying to run the notebook from [https://github.com/whylabs/whylogs-examples/blob/mainline/python/MLFlow%20Integration%20Example.ipynb](url) but after finishing all the mlflow runs, no profile data is saved on them.

I am running python 3.9.7.

**Comment by FelipeAdachi** [comment]
Hi @pimonteiro !

We just updated [the notebook](https://github.com/whylabs/whylogs-examples/blob/mainline/python/MLFlow%20Integration%20Example.ipynb) with the fix. [This](https://github.com/whylabs/whylogs-examples/pull/30) is the related PR.

The issue was a missing `.whylogs.yaml` configuration file. Now the example is using `.whylogs_mlflow.yaml` to create the session:

`session = get_or_create_session(".whylogs_mlflow.yaml")`

Now the updated notebook should be working.
Please, let me know if you run into any other issues with it!

**Comment by pimonteiro** [comment]
I can confirm it works as expected! Thank you for the help :)

@FelipeAdachi On another note, exploring a bit the knowledge you own on whylogs, is there a way to retrieve all the variable names from the profiles?

**Comment by FelipeAdachi** [comment]
I'm glad it's working! :)

Yes, you can access the column names for each profile with `.columns`. In the mlflow example, that would be, for example:

`mlflow_profiles[0].columns`

If you want the names for the profiles as a whole, you could also merge all of the profiles and then getting the names, again, with `.columns`:

```python
from functools import reduce

merged = reduce(lambda x, y: x.merge(y), mlflow_profiles)
merged.columns
```

**Comment by pimonteiro** [comment]
Thank you so much for your help :)
