### ISSUE TITLE
Why logs in Google Colab

### ISSUE THREAD

**Issue by aswinvk28** [whylabs/whylogs#534]
![image](https://user-images.githubusercontent.com/1046939/162749458-acdb4686-09c7-4df2-a005-aa8d254b3123.png)

Whylogs do not appear in the folder. 

Do you know why it keeps repeating?

Please check the folder and code here. [https://github.com/whylabs/whylogs/issues/521](https://github.com/whylabs/whylogs/issues/521)

```python
session = get_or_create_session()
logger = session.logger(dataset_name="test_dataset")
logger.log_dataframe(data)
logger.flush()
logger.close()
```

**Comment by aswinvk28** [comment]
![image](https://user-images.githubusercontent.com/1046939/162751904-47969b7f-134c-41d2-9e27-36b77d619246.png)

Here are the settings I used for the same.

**Comment by aswinvk28** [comment]
Ok, it's working in my local machine due to **AWS credentials**. Thanks for this. 

I find it excellent.

**Comment by jamie256** [comment]
Sounds like your issue is resolved? Note that the local 'output' folder would only be created if you have writers of type 'local' configured with that output folder specified (which is a default) and also flush a profile to disk.
Here is another example of a configuration file for local json output:
https://github.com/whylabs/whylogs/blob/mainline/examples/.whylogs_local.yaml#L17-L22

Here is an s3 example config file:
https://github.com/whylabs/whylogs/blob/mainline/examples/.whylogs_s3.yaml

 Let us know if you see issues here and I can take a closer look.
