### ISSUE TITLE
We shouldn't have the pip install commands commented out in our examples

### ISSUE THREAD

**Issue by jamie256** [whylabs/whylogs#835]
## Description

If a user just runs our notebooks they get errors because the pip install cell is commented out by default with instructions to run if they need. But running pip install when whylogs is already present is fine, and if they don't read the instructions things look broken.

Lets make things not broken in first impression scenarios.

**Comment by FelipeAdachi** [comment]
I agree.

The reason this is being done is because of notebook testing - if we install whylogs on the test environment, we wouldn't be able to check for bugs for the latest commits, only for the stable version. Neiter new features that won't be present when you install it.

Unless the pip install wouldn't override the environment's current whylogs, but I'm not sure what is the behavior in this case.

Any thoughts on how to address this?

**Comment by jamie256** [comment]
It shouldn't override, because we aren't installing --upgrade, so the pre test step already does `poetry install` and the test notebooks pip install whylogs step should all be satisfied by the pre test setup.
